In [1]:
import torch
import numpy as np

In [3]:
x = torch.empty(5,3) #空の行列(0になる事は保証されていない) #5行3列
print(x)

tensor([[3.4059e-15, 7.3988e+31, 4.4849e+21],
        [2.7370e+20, 6.4640e-04, 7.9290e+29],
        [7.5546e+31, 1.6932e+22, 6.9722e+22],
        [1.7973e+19, 2.9967e+32, 1.7743e+28],
        [2.0535e-19, 1.4609e-19, 1.0899e+27]])


In [5]:
x = torch.rand(5,3) #0～1の乱数
print(x)

tensor([[0.7829, 0.7024, 0.3109],
        [0.2846, 0.6056, 0.5655],
        [0.3939, 0.3017, 0.7506],
        [0.4169, 0.5683, 0.0900],
        [0.4408, 0.2117, 0.5746]])


In [6]:
torch.zeros(5,3, dtype=torch.long) #0

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [7]:
torch.tensor([1.23,3]) #べた書きで書いてtensorのデータ型を作る事もできる

tensor([1.2300, 3.0000])

In [8]:
x = x.new_ones(5,3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [10]:
x = torch.randn_like(x,dtype=torch.float) #randn:正規分布 #like:5行3列の形をそのまま継承 #中身をfloatに
print(x)

tensor([[ 0.4518,  1.0128,  1.2137],
        [ 0.9782,  1.9880, -0.3641],
        [ 0.9770, -0.6602,  1.1232],
        [-0.2150, -0.4910, -1.2456],
        [-1.0996, -0.3965, -0.2835]])


In [13]:
x = torch.arange(0,19,2) #0から18までを2個とばし
print(x)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])


In [15]:
x = torch.linspace(0,3,4) #要素の数を指定 #0～3の範囲で4つの要素を自動生成
print(x)

tensor([0., 1., 2., 3.])


In [17]:
x = torch.FloatTensor([5,6,7]) #float型で確実に作る場合
print(x)
print(x.dtype)

tensor([5., 6., 7.])
torch.float32


In [18]:
x = torch.tensor([5,6,7],dtype=torch.int) #このような形でもデータ型を指定できる。

In [19]:
print(x.dtype)

torch.int32


In [22]:
torch.manual_seed(42) #乱数を発生させるアルゴリズムのキー #これを指定しておくと、(同じセル内では)正規分布等を発生する時に毎回同じ結果を得られる
x = torch.rand(2,3)
print(x)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


In [25]:
x = torch.rand(2,3)
print(x)

tensor([[0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317]])
