In [1]:
import torch
import numpy as np

In [2]:
x = torch.empty(5,3) #空の行列(0になる事は保証されていない) #5行3列
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [3]:
x = torch.rand(5,3) #0～1の乱数
print(x)

tensor([[0.8764, 0.4671, 0.9616],
        [0.5392, 0.4425, 0.1219],
        [0.8769, 0.3509, 0.5185],
        [0.4623, 0.6700, 0.9862],
        [0.2600, 0.7415, 0.9099]])


In [4]:
torch.zeros(5,3, dtype=torch.long) #0

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [5]:
torch.tensor([1.23,3]) #べた書きで書いてtensorのデータ型を作る事もできる

tensor([1.2300, 3.0000])

In [6]:
x = x.new_ones(5,3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [7]:
x = torch.randn_like(x,dtype=torch.float) #randn:正規分布 #like:5行3列の形をそのまま継承 #中身をfloatに
print(x)

tensor([[ 1.7562,  0.6248, -1.2430],
        [ 0.1463, -1.2633,  0.6758],
        [-1.2986,  1.1898,  0.6368],
        [ 1.0611, -0.4355,  0.4869],
        [-3.1185, -0.2493,  0.1326]])


In [8]:
x = torch.arange(0,19,2) #0から18までを2個とばし
print(x)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])


In [9]:
x = torch.linspace(0,3,4) #要素の数を指定 #0～3の範囲で4つの要素を自動生成
print(x)

tensor([0., 1., 2., 3.])


In [10]:
x = torch.FloatTensor([5,6,7]) #float型で確実に作る場合
print(x)
print(x.dtype)

tensor([5., 6., 7.])
torch.float32


In [11]:
x = torch.tensor([5,6,7],dtype=torch.int) #このような形でもデータ型を指定できる。

In [12]:
print(x.dtype)

torch.int32


In [13]:
torch.manual_seed(42) #乱数を発生させるアルゴリズムのキー #これを指定しておくと、(同じセル内では)正規分布等を発生する時に毎回同じ結果を得られる
x = torch.rand(2,3)
print(x)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


In [14]:
x = torch.rand(2,3)
print(x)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])


In [15]:
x.dtype #データ型を取得

torch.float32

In [16]:
x.size() #マトリクスのサイズ #何行何列か

torch.Size([2, 3])

In [17]:
x.shape #マトリクスのサイズ #何行何列か

torch.Size([2, 3])

In [18]:
x = torch.rand(5,3) #ダミーデータ #0～1の乱数
print(x)

tensor([[0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739],
        [0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317],
        [0.1053, 0.2695, 0.3588]])


In [19]:
y = torch.rand(5,3) #ダミーデータ #0～1の乱数
print(y)

tensor([[0.1994, 0.5472, 0.0062],
        [0.9516, 0.0753, 0.8860],
        [0.5832, 0.3376, 0.8090],
        [0.5779, 0.9040, 0.5547],
        [0.3423, 0.6343, 0.3644]])


In [20]:
print(x + y) #テンソルの足し算ができる。#対応する要素同士の演算

tensor([[1.0688, 1.1149, 0.7473],
        [1.3810, 0.9607, 1.4599],
        [0.8498, 0.9651, 1.0786],
        [1.0193, 1.2009, 1.3863],
        [0.4476, 0.9038, 0.7232]])


In [21]:
result = torch.empty(5,3) #空のテンソル
torch.add(x,y, out=result) #出力の結果をresultに代入

tensor([[1.0688, 1.1149, 0.7473],
        [1.3810, 0.9607, 1.4599],
        [0.8498, 0.9651, 1.0786],
        [1.0193, 1.2009, 1.3863],
        [0.4476, 0.9038, 0.7232]])

In [22]:
y.add_(x) #yにxを足す
print(y)

tensor([[1.0688, 1.1149, 0.7473],
        [1.3810, 0.9607, 1.4599],
        [0.8498, 0.9651, 1.0786],
        [1.0193, 1.2009, 1.3863],
        [0.4476, 0.9038, 0.7232]])


In [23]:
print(y[:,1]) #[行は全部取得, 列は1列目だけ取得] #「:」スライス

tensor([1.1149, 0.9607, 0.9651, 1.2009, 0.9038])


In [24]:
print(y[0,:]) #[行は0行目だけ取得, 列は全部取得]

tensor([1.0688, 1.1149, 0.7473])


In [25]:
print(y[2:,1:]) #[行は2行目以降全部, 列は1列目以降全部]

tensor([[0.9651, 1.0786],
        [1.2009, 1.3863],
        [0.9038, 0.7232]])


In [26]:
x = torch.randn(4, 4)
y = x.view(16) #16個の要素にする
z = x.view(-1, 8) # -1:自動計算 #列が8の場合に、自動的に行が2となる。
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [27]:
x = torch.randn(1) #テンソルで表現された値はテンソルオブジェクトで返ってくる。
print(x)
print(x.item()) #数値そのものが返ってくる。 #numpy等で使える

tensor([0.5200])
0.5199637413024902


In [28]:
a = torch.ones(3) #tensor型
print(a)

tensor([1., 1., 1.])


In [29]:
b = a.numpy() #numpy型へ変換
print(b)

[1. 1. 1.]


In [30]:
a.add_(3) #aとbはメモリを共有しているので、aの値を変更するとbも変更される。
print(a)
print(b)

tensor([4., 4., 4.])
[4. 4. 4.]


In [31]:
a = np.ones(3) #nuympyのデータ列
print(a)

[1. 1. 1.]


In [33]:
b = torch.from_numpy(a) #tensor型へ変換
print(b)

tensor([1., 1., 1.], dtype=torch.float64)


In [34]:
a = torch.arange(1, 4, 1, dtype=torch.float) #ダミーのデータ列 
print(a)

tensor([1., 2., 3.])


In [35]:
a.mean() #tensor型の平均

tensor(2.)

In [36]:
a.sum() #tensor型の総和

tensor(6.)

In [37]:
print(a.max()) #最大
print(a.min()) #最小

tensor(3.)
tensor(1.)


In [38]:
a = torch.tensor([1,2,3], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)

print(torch.add(a,b).sum()) #足して、その総和をとる

tensor(21.)


In [39]:
import math
a = torch.tensor([math.radians(30), math.radians(60), math.radians(90)])

In [41]:
#三角関数
print(torch.sin(a))
print(torch.cos(a))
print(torch.tan(a))
print(torch.asin(a))
print(torch.acos(a))
print(torch.tanh(a))

tensor([0.5000, 0.8660, 1.0000])
tensor([ 8.6603e-01,  5.0000e-01, -4.3711e-08])
tensor([ 5.7735e-01,  1.7321e+00, -2.2877e+07])
tensor([0.5511,    nan,    nan])
tensor([1.0197,    nan,    nan])
tensor([0.4805, 0.7807, 0.9172])


In [43]:
a = torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float)
b = torch.tensor([[1,2],[3,4],[5,6]],dtype=torch.float)

In [44]:
torch.mm(a,b) #行列の掛け算

tensor([[22., 28.],
        [49., 64.]])

In [45]:
print(a@b) #行列の掛け算

tensor([[22., 28.],
        [49., 64.]])
